import fs from 'node:fs/promises';
import path from 'node:path';
import unzipper from 'unzipper';
import { detectProject } from './detect.js';
import { DemoStaticProvider } from './providers/demo-static.js';
const maxExtract = Number(process.env.EXTRACT_MAX_SIZE || 1073741824);
const safePath = (root, entry) => { const normalized = path.posix.normalize(entry.replaceAll('\\','/')); if (normalized.startsWith('/') || normalized.split('/').includes('..')) throw new Error('Unsafe ZIP path'); const target=path.resolve(root, normalized); if(target!==root && !target.startsWith(root+path.sep)) throw new Error('Unsafe ZIP path'); return target; };
async function extract(buffer, dest){ const directory=await unzipper.Open.buffer(buffer); let total=0, count=0; for(const entry of directory.files){ if(++count>10000 || entry.type==='SymbolicLink') throw new Error('ZIP contains unsafe entries'); const target=safePath(dest,entry.path); if(entry.type==='Directory'){await fs.mkdir(target,{recursive:true}); continue;} const chunks=[]; let size=0; for await(const chunk of entry.stream()){ size+=chunk.length; total+=chunk.length; if(total>maxExtract) throw new Error('ZIP expands beyond the extraction limit'); chunks.push(chunk); } await fs.mkdir(path.dirname(target),{recursive:true}); await fs.writeFile(target,Buffer.concat(chunks)); } }
export async function createPipeline({id,file,root,registry}){ const work=path.join(root,id); await fs.rm(work,{recursive:true,force:true}); await fs.mkdir(work,{recursive:true}); registry.update(id,{status:'Extracting',deploymentPath:work}); registry.log(id,'Extracting ZIP...'); await extract(file.buffer,work); registry.update(id,{status:'Detecting project'}); registry.log(id,'Checking project structure...'); const project=await detectProject(work); registry.log(id,`Detected ${project.label}.`); if(project.kind!=='static'){ registry.log(id,'This safe development provider publishes pre-built static files only.'); throw new Error('This project needs an isolated production build provider.'); } registry.update(id,{status:'Deploying'}); registry.log(id,'Creating deployment artifact...'); const provider=new DemoStaticProvider(); await provider.deploy({directory:project.directory}); registry.update(id,{status:'Configuring website'}); registry.log(id,'Routing registry updated.'); registry.update(id,{status:'Live'}); registry.log(id,'Deployment is live.'); }
